
package br.com.project.sarti.view;

import br.com.project.sarti.dao.ItemVendaDAO;
import br.com.project.sarti.dao.ProdutosDAO;
import br.com.project.sarti.dao.VendasDAO;
import br.com.project.sarti.model.Clientes;
import br.com.project.sarti.model.ItemVenda;
import br.com.project.sarti.model.Produtos;
import br.com.project.sarti.model.Vendas;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmPagamentos extends javax.swing.JFrame {
    
    Clientes clienteId = new Clientes();
    DefaultTableModel carrinho;

    public FrmPagamentos() {
        initComponents();
        
        txtcartao.setText("0");
        txtdinheiro.setText("0");
        txtcheque.setText("0");
        txttroco.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelCadastroCli = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtdinheiro = new javax.swing.JTextField();
        txtcartao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcheque = new javax.swing.JTextField();
        txttroco = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnFinalizarVenda = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Pagamentos");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        LabelCadastroCli.setBackground(new java.awt.Color(255, 255, 255));
        LabelCadastroCli.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        LabelCadastroCli.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastroCli.setText("Pagamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(LabelCadastroCli)
                .addContainerGap(551, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(LabelCadastroCli)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 120);

        jLabel5.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel5.setText("Obs.:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 140, 70, 33);

        txtdinheiro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtdinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdinheiroActionPerformed(evt);
            }
        });
        getContentPane().add(txtdinheiro);
        txtdinheiro.setBounds(170, 140, 240, 40);

        txtcartao.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtcartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcartaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcartao);
        txtcartao.setBounds(170, 200, 240, 40);

        jLabel6.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel6.setText("TOTAL:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 390, 140, 33);

        txtcheque.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtcheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchequeActionPerformed(evt);
            }
        });
        getContentPane().add(txtcheque);
        txtcheque.setBounds(170, 260, 240, 40);

        txttroco.setEditable(false);
        txttroco.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txttroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttrocoActionPerformed(evt);
            }
        });
        getContentPane().add(txttroco);
        txttroco.setBounds(170, 320, 240, 40);

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        getContentPane().add(txttotal);
        txttotal.setBounds(170, 380, 240, 40);

        jLabel10.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel10.setText("CARTÃO:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 210, 140, 33);

        jLabel11.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel11.setText("CHEQUE:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 270, 140, 33);

        jLabel12.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel12.setText("TROCO:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 330, 140, 33);

        btnFinalizarVenda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFinalizarVenda.setText("Finalizar Venda");
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizarVenda);
        btnFinalizarVenda.setBounds(130, 460, 260, 60);

        jLabel7.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel7.setText("DINHEIRO:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 150, 140, 33);

        txtObs.setColumns(20);
        txtObs.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(510, 130, 280, 110);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtdinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdinheiroActionPerformed

    private void txtcartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcartaoActionPerformed

    private void txtchequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchequeActionPerformed

    private void txttrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttrocoActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        
        double pcartao, pcheque, pdinheiro, totalpago, totalvenda, troco;
        //receber os valores
        pcartao = Double.parseDouble(txtcartao.getText());
        pcheque = Double.parseDouble(txtcheque.getText());
        pdinheiro = Double.parseDouble(txtdinheiro.getText());
        
        totalvenda = Double.parseDouble(txttotal.getText());
        
        totalpago = pcartao + pcheque + pdinheiro;

        //calcular troco
        troco = totalpago - totalvenda;
        txttroco.setText(String.valueOf(troco));
        
        Vendas objv = new Vendas();
        //dados do cliente (cliente_id)
        objv.setCliente(clienteId);
        
        //pega a data atual
         Date agora = new Date();
        SimpleDateFormat dataEUA = new SimpleDateFormat("yyyy/MM/dd");
        String datamysql = dataEUA.format(agora);
        objv.setData_venda(datamysql);
        //TOTAL DA VENDA 
        objv.setTotal_venda(totalvenda);
        objv.setObs(txtObs.getText());
        
        VendasDAO dao_v = new VendasDAO();
        dao_v.cadastrarVenda(objv);
        
        //retornar o id da ultima venda realizada
        
        objv.setId(dao_v.retornaUltimaVenda());
        //System.out.println(" Id da Ultima venda " + objv.getId());
        //cadastrando os produtos na tabela itemvendas
        for(int i = 0; i < carrinho.getRowCount(); i++){
           int qtd_estoque, qtd_comprada, qtd_atualizada;
            Produtos objp = new Produtos();
            ProdutosDAO dao_produto = new ProdutosDAO();
            ItemVenda item = new ItemVenda();
            item.setVenda(objv);
            
            objp.setId(Integer.parseInt(carrinho.getValueAt(i, 0).toString()));
            item.setProduto(objp);
            item.setQtd(Integer.parseInt(carrinho.getValueAt(i, 2).toString()));
            item.setSubtotal(Double.parseDouble(carrinho.getValueAt(i, 4).toString()));
            
            //baixa no estoque
            qtd_estoque = dao_produto.retornaEstoqueAtual(objp.getId());
            qtd_comprada = Integer.parseInt(carrinho.getValueAt(i, 2).toString());
            qtd_atualizada = qtd_estoque - qtd_comprada;
            dao_produto.baixaEstoque(objp.getId(), qtd_atualizada);
            
            ItemVendaDAO daoitem = new ItemVendaDAO();
            daoitem.cadastrarItem(item);       
        }
     /************************************************/
        JOptionPane.showMessageDialog(null,"Venda Registrada com Sucesso!!");

        
      
    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCadastroCli;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtcartao;
    private javax.swing.JTextField txtcheque;
    private javax.swing.JTextField txtdinheiro;
    public javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttroco;
    // End of variables declaration//GEN-END:variables
}
